POST http://localhost:3000/customers/nuevoCliente
Content-Type: application/json

{
  "cedula": "1751459048",
  "nombre": "Dylan",
  "celular": "0962823354",
  "celular_opcional": "2600505228",
  "email": "dylanhhh@hotmail.com"
}

###
### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###